setting:
  1:
    delay: 0
    texture:
      translate-x: 0
      translate-y: 2.53
      translate-z: 0
      rotate-x: 90
      rotate-y: 0
      rotate-z: 50
      path: ""
      follow-player-eyes: false
    animations:
      scale-animation:
        delay: 0
        from-scale: 11
        to-scale: 10
        duration: 3000
        cycle-count: 1
        fixed: true
        resetTime: 0
      rotate-animation:
        direction: z
        delay: 0
        angle: 360
        duration: 6000
        cycle-count: -1
        fixed: false
  2:
    delay: 0
    texture:
      translate-x: 0
      translate-y: 2.53
      translate-z: 0
      rotate-x: 45
      rotate-y: 0
      rotate-z: 0
      path: bloom/魂环/h5_3.png
      follow-player-eyes: false
    animations:
      scale-animation:
        delay: 0
        from-scale: 11
        to-scale: 10
        duration: 3000
        cycle-count: 1
        fixed: true
        resetTime: 0
      rotate-animation:
        direction: z
        delay: 0
        angle: 360
        duration: 6000
        cycle-count: -1
        fixed: false
